defaults: &defaults
  rabbitmq_url: <%= ENV.fetch('RABBITMQ_URL'){ "amqp://rabbit:rabbit@localhost:5672" } %>
  slicer_script: <%= ENV.fetch('SLICER_SCRIPT_PATH') { "/Applications/Slic3r.app/Contents/MacOS/slic3r" } %>
  repo_mount_path: <%= ENV.fetch('REPO_MOUNT_PATH') { "../repos"} %>
  mixpanel_token: <%= ENV.fetch('MIXPANEL_TOKEN') { "514c0bd2f3d0d61f7aff166a9ac4a95a" } %>
  smtp_username: <%= ENV.fetch('SMTP_USERNAME') { "noreply@mg.layerkeep.com" } %>
  smtp_password: <%= ENV.fetch('SMTP_PASSWORD') { "1a2d3bf61049a0d4ae97043cc4da065d-29b7488f-73824278" } %>
  thingiverse_api_token: <%= ENV.fetch('THINGIVERSE_API_TOKEN') { "13dd7dc6887cf4c5244cc81cd727bf8b" } %>

development:
  <<: *defaults
  rabbitmq_vhost: '/'  


staging:
  <<: *defaults
  rabbitmq_vhost: 'staging'

test:
  <<: *defaults
  rabbitmq_vhost: 'test'  

production:
  <<: *defaults
  rabbitmq_vhost: '/'  
  mixpanel_token: <%= ENV.fetch('MIXPANEL_TOKEN') { "2424f09396a8104a463a4a7b3dca2786" } %>