defaults: &defaults
  rabbitmq_url: <%= ENV.fetch('RABBITMQ_URL'){ "amqp://rabbit:rabbit@localhost:5672" } %>
  rabbitmq_api_url: <%= ENV.fetch('rabbitmq_api_url') { "http://guest:guest@localhost:15672" } %>  
  slicer_script: <%= ENV.fetch('SLICER_SCRIPT_PATH') { "/Applications/Slic3r.app/Contents/MacOS/slic3r" } %> 
  openscad: <%= ENV.fetch('OPENSCAD_PATH') { "/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD" } %> 
  openscad_script: <%= ENV.fetch('OPENSCAD_SCRIPT_PATH') { Rails.root.to_s + "/services/scripts/scad.sh" } %> 
  repo_mount_path: <%= ENV.fetch('REPO_MOUNT_PATH') { "../repos"} %>
  mixpanel_token: <%= ENV.fetch('MIXPANEL_TOKEN') { "514c0bd2f3d0d61f7aff166a9ac4a95a" } %>
  smtp_username: <%= ENV.fetch('SMTP_USERNAME') { "noreply@mg.layerkeep.com" } %>
  smtp_password: <%= ENV.fetch('SMTP_PASSWORD') { "1a2d3bf61049a0d4ae97043cc4da065d-29b7488f-73824278" } %>

development:
  <<: *defaults
  rabbitmq_vhost: '/'  


staging:
  <<: *defaults
  rabbitmq_vhost: 'staging'

test:
  <<: *defaults
  rabbitmq_vhost: 'test'  

production:
  <<: *defaults
  rabbitmq_vhost: '/'  
  mixpanel_token: <%= ENV.fetch('MIXPANEL_TOKEN') { "2424f09396a8104a463a4a7b3dca2786" } %>